# Paths
path=(
  /usr/local/opt/coreutils/libexec/gnubin
  /usr/local/opt/go/libexec/bin
  $DOTFILES/bin
  /usr/local/{sbin,bin}
  /usr/{sbin,bin}
  /{sbin,bin}
  /Applications/Postgres.app/Contents/Versions/latest/bin
  $HOME/Library/Haskell/bin
  $HOME/.local/bin
)

cdpath=(
  $HOME
  $HOME/code
  $HOME/code/work
  $HOME/Downloads
)

fpath=(
  /usr/local/share/zsh-completions
  $DOTFILES/completions
  $DOTFILES/zsh/zfunctions
  $fpath
)

manpath=(
  /usr/local/opt/coreutils/libexec/gnuman
  $DOTFILES/man/man1
)

# Ensure path arrays do not contain duplicates.
typeset -gU path cdpath fpath manpath

# load rbenv if available
if command -v rbenv >/dev/null; then
  eval "$(rbenv init - --no-rehash)"
fi

# load nodenv if available
if command -v nodenv >/dev/null; then
  eval "$(nodenv init -)"
fi

# vim: ft=zsh sw=2 ts=2 et
