# Use vim as the visual editor
export VISUAL='mvim -v'
export EDITOR=$VISUAL

# Reduce to 0.1 secs the delay after hitting the <ESC> key.
export KEYTIMEOUT=1

DOTFILES="$HOME/.dotfiles"
ZSH="$HOME/.zsh"
ZSH_CACHE_DIR="$ZSH/cache/"

# Set Ag as the default source for fzf
export FZF_DEFAULT_COMMAND='ag --hidden -g ""'
